title: Julien Dequaire's Den
email: julien.dequaire@gmail.com
description: >-
  Just a little of me, exploration, implementation and concepts
baseurl: ""
url: "juliendequaire.github.io"
twitter_username: juliendequaire
github_username:  juliendequaire

theme: minima
plugins:
  - jekyll-feed
