title: Julien Dequaire personnal blog
author:
  name: Julien Dequaire
  email: julien.dequaire@gmail.com
description: >
  Julien Dequaire's personnal blog

show_excerpts: false

minima:
  date_format: "%b %-d, %Y"

  social_links:
    twitter: juliendequaire
    github:  juliendequaire
    linkedin: juliendequaire

header_pages:
 - about.md

theme: minima

minima:
  skin: dark

plugins:
 - jekyll-feed
 - jekyll-seo-tag
